# Generated by Django 5.0.14 on 2026-09-29 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('credencial', models.IntegerField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_final', models.DateTimeField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('sanciones', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prestamo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mensajes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipoPrestamo',
            fields=[
                ('prestamo', models.OneToOneField(db_column='prestamo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='prestamos.prestamo')),
            ],
            options={
                'db_table': 'equipo_prestamo',
                'managed': False,
            },
        ),
    ]
