# Generated by Django 5.0.14 on 2026-09-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionCasillero',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('llave', models.IntegerField(blank=True, null=True)),
                ('estatus', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asignacion_casillero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Casillero',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'casillero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoCasillero',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estado_casillero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodoEscolar',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'periodo_escolar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_movimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPeriodo',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_periodo',
                'managed': False,
            },
        ),
    ]
