# Generated by Django 5.0.14 on 2026-09-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_barras', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(max_length=150)),
                ('num_inter', models.CharField(blank=True, max_length=50, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('num_utt', models.CharField(blank=True, max_length=50, null=True)),
                ('rf_resguardo', models.CharField(blank=True, max_length=50, null=True)),
                ('resguardante', models.CharField(blank=True, max_length=50, null=True)),
                ('resguardo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'equipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoEquipo',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estado_equipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('clave', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'marca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'modelo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_equipo',
                'managed': False,
            },
        ),
    ]
